core.override_item("scifi_nodes:Doom_door_closed", {use_texture_alpha = "clip"})
core.override_item("scifi_nodes:Doom_door_opened", {use_texture_alpha = "clip"})
core.override_item("scifi_nodes:Doom_door_closed_top", {use_texture_alpha = "clip"})
core.override_item("scifi_nodes:Doom_door_opened_top", {use_texture_alpha = "clip"})
core.override_item("scifi_nodes:blue_door_closed", {use_texture_alpha = "clip"})
core.override_item("scifi_nodes:blue_door_opened", {use_texture_alpha = "clip"})
core.override_item("scifi_nodes:blue_door_closed_top", {use_texture_alpha = "clip"})
core.override_item("scifi_nodes:blue_door_opened_top", {use_texture_alpha = "clip"})
